-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.affiliates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  affiliate_user_id uuid NOT NULL,
  commission_percent numeric NOT NULL DEFAULT 10 CHECK (commission_percent > 0::numeric AND commission_percent <= 100::numeric),
  is_active boolean DEFAULT true,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT affiliates_pkey PRIMARY KEY (id),
  CONSTRAINT fk_affiliates_creator FOREIGN KEY (creator_id) REFERENCES public.profiles(id),
  CONSTRAINT fk_affiliates_affiliate_user FOREIGN KEY (affiliate_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.conversion_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL,
  product_id uuid,
  order_id uuid,
  session_id text,
  event_type USER-DEFINED NOT NULL,
  revenue numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT conversion_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.coupons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  code text NOT NULL,
  discount_type USER-DEFINED NOT NULL,
  discount_value numeric NOT NULL CHECK (discount_value > 0::numeric),
  max_uses integer,
  current_uses integer DEFAULT 0 CHECK (current_uses >= 0),
  valid_from timestamp with time zone DEFAULT now(),
  valid_until timestamp with time zone,
  is_active boolean DEFAULT true,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT coupons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.creator_balances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL UNIQUE,
  total_earnings numeric NOT NULL DEFAULT 0,
  total_platform_fees numeric NOT NULL DEFAULT 0,
  total_paid_out numeric NOT NULL DEFAULT 0,
  pending_payout numeric NOT NULL DEFAULT 0,
  currency text DEFAULT 'INR'::text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT creator_balances_pkey PRIMARY KEY (id),
  CONSTRAINT fk_creator_balances_creator FOREIGN KEY (creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.creator_kyc (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text, 'expired'::text])),
  kyc_level text NOT NULL DEFAULT 'none'::text CHECK (kyc_level = ANY (ARRAY['none'::text, 'basic'::text, 'full'::text])),
  full_name text,
  legal_name text,
  dob date,
  gender text,
  pan_enc bytea,
  aadhaar_last4 text,
  upi_id_enc bytea,
  bank_account_enc bytea,
  ifsc_code text,
  pan_last4 text,
  pan_verified boolean DEFAULT false,
  pan_verified_at timestamp with time zone,
  pan_name text,
  pan_verification_provider text,
  pan_verification_ref text,
  bank_last4 text,
  bank_verified boolean DEFAULT false,
  bank_verified_at timestamp with time zone,
  bank_account_name text,
  bank_verification_provider text,
  bank_verification_ref text,
  beneficiary_id text,
  beneficiary_metadata jsonb DEFAULT '{}'::jsonb,
  upi_verified boolean DEFAULT false,
  upi_verified_at timestamp with time zone,
  upi_verification_provider text,
  upi_verification_ref text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  postal_code text,
  country text DEFAULT 'IN'::text,
  document_urls jsonb DEFAULT '{}'::jsonb,
  document_hashes jsonb DEFAULT '{}'::jsonb,
  verification_provider text,
  rejection_reason text,
  admin_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT creator_kyc_pkey PRIMARY KEY (id),
  CONSTRAINT fk_kyc_creator FOREIGN KEY (creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.creator_payout_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  type USER-DEFINED NOT NULL,
  is_default boolean DEFAULT false,
  upi_id text,
  account_holder_name text,
  account_number text,
  ifsc_code text,
  bank_name text,
  branch_name text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text])),
  metadata jsonb,
  version integer DEFAULT 1 CHECK (version > 0),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT creator_payout_methods_pkey PRIMARY KEY (id),
  CONSTRAINT fk_cpm_creator FOREIGN KEY (creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.creator_payout_request_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payout_request_id uuid NOT NULL,
  revenue_share_id uuid NOT NULL,
  amount numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT creator_payout_request_items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_cpri_request FOREIGN KEY (payout_request_id) REFERENCES public.creator_payout_requests(id)
);
CREATE TABLE public.creator_payout_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  payout_method_id uuid,
  amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'processed'::text])),
  admin_notes text,
  rejection_reason text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT creator_payout_requests_pkey PRIMARY KEY (id),
  CONSTRAINT fk_cpr_creator FOREIGN KEY (creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.creator_payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  payout_request_id uuid,
  payout_method_id uuid,
  amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  status text NOT NULL DEFAULT 'initiated'::text CHECK (status = ANY (ARRAY['initiated'::text, 'processed'::text, 'failed'::text])),
  gateway_name text DEFAULT 'cashfree'::text,
  gateway_payout_id text,
  gateway_batch_id text,
  gateway_metadata jsonb,
  initiated_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  failure_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT creator_payouts_pkey PRIMARY KEY (id),
  CONSTRAINT fk_payout_request FOREIGN KEY (payout_request_id) REFERENCES public.creator_payout_requests(id)
);
CREATE TABLE public.creator_revenue_shares (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  order_item_id uuid NOT NULL,
  creator_id uuid NOT NULL,
  subscription_id uuid,
  product_id uuid NOT NULL,
  gross_amount numeric NOT NULL CHECK (gross_amount > 0::numeric),
  platform_fee_percent numeric NOT NULL CHECK (platform_fee_percent >= 0::numeric AND platform_fee_percent <= 100::numeric),
  platform_fee_amount numeric NOT NULL CHECK (platform_fee_amount >= 0::numeric),
  creator_earnings_amount numeric NOT NULL CHECK (creator_earnings_amount >= 0::numeric),
  currency text DEFAULT 'INR'::text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'settled'::text, 'refunded'::text])),
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT creator_revenue_shares_pkey PRIMARY KEY (id),
  CONSTRAINT fk_crs_order FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT fk_crs_product FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT fk_crs_creator FOREIGN KEY (creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.creator_subscription_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  plan_id text NOT NULL,
  amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  status text DEFAULT 'created'::text CHECK (status = ANY (ARRAY['created'::text, 'paid'::text, 'failed'::text])),
  gateway_name text DEFAULT 'cashfree'::text,
  gateway_order_id text,
  gateway_payment_id text,
  gateway_signature text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  paid_at timestamp with time zone,
  CONSTRAINT creator_subscription_orders_pkey PRIMARY KEY (id),
  CONSTRAINT fk_cso_creator FOREIGN KEY (creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.email_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  creator_id uuid,
  order_id uuid,
  payout_request_id uuid,
  recipient_email text NOT NULL,
  subject text NOT NULL,
  template_name text NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text, 'bounced'::text])),
  sent_at timestamp with time zone,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_events_pkey PRIMARY KEY (id),
  CONSTRAINT fk_email_events_user FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_email_events_creator FOREIGN KEY (creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.forms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT forms_pkey PRIMARY KEY (id),
  CONSTRAINT forms_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.guest_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL,
  product_id uuid,
  full_name text,
  email text,
  mobile text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'converted'::text])),
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT guest_leads_pkey PRIMARY KEY (id),
  CONSTRAINT fk_guest_leads_site FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.lead_form (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  form_id uuid NOT NULL,
  site_id uuid NOT NULL,
  full_name text,
  email text,
  mobile text,
  other jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_form_pkey PRIMARY KEY (id),
  CONSTRAINT lead_form_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id)
);
CREATE TABLE public.linkinbio_blocks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  page_id uuid NOT NULL,
  type text NOT NULL,
  content jsonb NOT NULL DEFAULT '{}'::jsonb,
  style jsonb NOT NULL DEFAULT '{}'::jsonb,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  sort_order integer NOT NULL DEFAULT 0,
  is_visible boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT linkinbio_blocks_pkey PRIMARY KEY (id),
  CONSTRAINT fk_linkinbio_blocks_page FOREIGN KEY (page_id) REFERENCES public.linkinbio_pages(id)
);
CREATE TABLE public.linkinbio_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  block_id uuid NOT NULL,
  type text NOT NULL DEFAULT 'link'::text,
  title text NOT NULL DEFAULT ''::text,
  description text NOT NULL DEFAULT ''::text,
  url text NOT NULL DEFAULT ''::text,
  thumbnail_url text NOT NULL DEFAULT ''::text,
  product_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  sort_order integer NOT NULL DEFAULT 0,
  is_visible boolean NOT NULL DEFAULT true,
  click_count bigint NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT linkinbio_items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_linkinbio_items_block FOREIGN KEY (block_id) REFERENCES public.linkinbio_blocks(id),
  CONSTRAINT fk_linkinbio_items_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.linkinbio_pages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL UNIQUE,
  display_name text NOT NULL DEFAULT ''::text,
  bio text,
  avatar_url text,
  cover_url text,
  theme jsonb NOT NULL DEFAULT '{}'::jsonb,
  layout jsonb NOT NULL DEFAULT '{}'::jsonb,
  seo jsonb NOT NULL DEFAULT '{"title": "", "description": ""}'::jsonb,
  settings jsonb NOT NULL DEFAULT '{"showWatermark": true, "showShareButton": true}'::jsonb,
  published boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT linkinbio_pages_pkey PRIMARY KEY (id),
  CONSTRAINT fk_linkinbio_pages_site FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.media_library (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  storage_file_id uuid,
  file_name text NOT NULL,
  file_type text NOT NULL,
  file_size bigint NOT NULL CHECK (file_size > 0),
  media_type text NOT NULL CHECK (media_type = ANY (ARRAY['image'::text, 'video'::text, 'document'::text, 'other'::text])),
  storage_url text NOT NULL,
  thumbnail_url text,
  duration_seconds integer,
  width integer,
  height integer,
  alt_text text,
  description text,
  tags ARRAY,
  is_favorite boolean DEFAULT false,
  usage_count integer DEFAULT 0,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT media_library_pkey PRIMARY KEY (id),
  CONSTRAINT fk_media_library_creator FOREIGN KEY (creator_id) REFERENCES public.profiles(id),
  CONSTRAINT fk_media_library_storage FOREIGN KEY (storage_file_id) REFERENCES public.storage_files(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_user_id uuid,
  recipient_creator_id uuid,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['sale'::text, 'refund'::text, 'payout'::text, 'review'::text, 'kyc_reminder'::text, 'kyc_rejected'::text, 'order'::text, 'wallet'::text])),
  is_read boolean DEFAULT false,
  action_url text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT fk_notif_user FOREIGN KEY (recipient_user_id) REFERENCES public.users(id),
  CONSTRAINT fk_notif_creator FOREIGN KEY (recipient_creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  product_id uuid,
  price_at_purchase numeric NOT NULL,
  quantity integer DEFAULT 1,
  origin_site_id uuid,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_oi_order FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT fk_oi_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.order_referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  referral_code_id uuid NOT NULL,
  referrer_creator_id uuid,
  referred_user_id uuid,
  commission_amount numeric,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'settled'::text])),
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_referrals_pkey PRIMARY KEY (id),
  CONSTRAINT fk_order_referrals_order FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT fk_order_referrals_creator FOREIGN KEY (referrer_creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  origin_site_id uuid,
  guest_lead_id uuid,
  total_amount numeric NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'refunded'::text, 'cancelled'::text])),
  customer_name text,
  customer_email text,
  customer_phone text,
  payment_method text,
  gateway_name text DEFAULT 'cashfree'::text,
  gateway_order_id text,
  gateway_payment_id text,
  gateway_signature text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_orders_guest_lead FOREIGN KEY (guest_lead_id) REFERENCES public.guest_leads(id)
);
CREATE TABLE public.payment_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL,
  slug text,
  title text NOT NULL,
  description text,
  amount numeric,
  is_fixed_amount boolean DEFAULT true,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_request_id uuid NOT NULL,
  customer_name text NOT NULL,
  customer_email text NOT NULL,
  customer_phone text NOT NULL,
  amount numeric NOT NULL,
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text])),
  payment_method text,
  transaction_id text,
  gateway_name text DEFAULT 'cashfree'::text,
  gateway_order_id text,
  gateway_payment_id text,
  gateway_signature text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_payment_submission_request FOREIGN KEY (payment_request_id) REFERENCES public.payment_requests(id)
);
CREATE TABLE public.product_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  creator_id uuid NOT NULL,
  file_label text NOT NULL,
  storage_url text NOT NULL,
  storage_file_id uuid,
  file_type text,
  file_size_bytes bigint,
  version text DEFAULT '1.0'::text,
  is_primary boolean DEFAULT false,
  download_count integer DEFAULT 0,
  checksum text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_files_pkey PRIMARY KEY (id),
  CONSTRAINT fk_pf_product FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT fk_pf_storage FOREIGN KEY (storage_file_id) REFERENCES public.storage_files(id),
  CONSTRAINT fk_pf_creator FOREIGN KEY (creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.product_licenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  order_item_id uuid NOT NULL,
  user_id uuid,
  product_id uuid NOT NULL,
  license_key text,
  license_type text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'revoked'::text, 'expired'::text])),
  issued_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  snapshot jsonb,
  CONSTRAINT product_licenses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.product_view_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  site_id uuid,
  session_id text,
  referrer text,
  device_type USER-DEFINED,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT product_view_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  price numeric NOT NULL DEFAULT 0.00 CHECK (price >= 0::numeric),
  stock_count integer,
  thumbnail_url text,
  category text,
  is_published boolean DEFAULT false,
  is_on_discover_page boolean DEFAULT false,
  images jsonb DEFAULT '[]'::jsonb,
  content jsonb,
  metadata jsonb,
  product_link text,
  post_purchase_url text,
  post_purchase_instructions text,
  is_licensable boolean DEFAULT false,
  license_type text,
  license_terms text,
  license_metadata jsonb,
  search_vector tsvector,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT fk_products_creator FOREIGN KEY (creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  full_name text,
  avatar_url text,
  mobile text,
  mobile_verified boolean DEFAULT false,
  email text UNIQUE,
  email_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.public_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  url text NOT NULL,
  name text NOT NULL DEFAULT ''::text,
  category text NOT NULL DEFAULT 'general'::text,
  tags ARRAY DEFAULT '{}'::text[],
  width integer,
  height integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT public_images_pkey PRIMARY KEY (id)
);
CREATE TABLE public.referral_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  owner_user_id uuid,
  owner_creator_id uuid,
  is_active boolean DEFAULT true,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT referral_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.site_design_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL UNIQUE,
  creator_id uuid NOT NULL,
  color_palette jsonb NOT NULL DEFAULT '{"text": "#111827", "muted": "#6B7280", "accent": "#EC4899", "primary": "#6366F1", "surface": "#F9FAFB", "secondary": "#8B5CF6"}'::jsonb,
  typography jsonb NOT NULL DEFAULT '{"body_font": "Inter", "scale_ratio": 1.25, "base_size_px": 16, "heading_font": "Inter"}'::jsonb,
  spacing_scale jsonb NOT NULL DEFAULT '{"lg": 24, "md": 16, "sm": 8, "xl": 32, "xs": 4, "2xl": 48, "base_px": 4}'::jsonb,
  border_radius_scale jsonb NOT NULL DEFAULT '{"lg": "12px", "md": "8px", "sm": "4px", "xl": "16px", "full": "9999px"}'::jsonb,
  shadow_presets jsonb DEFAULT '[]'::jsonb,
  custom_css_variables jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_design_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT fk_design_tokens_creator FOREIGN KEY (creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.site_main (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL UNIQUE,
  title text NOT NULL,
  description text,
  logo_url text,
  banner_url text,
  template_name text DEFAULT 'default'::text,
  theme jsonb DEFAULT '{"primaryColor": "#6366F1", "backgroundColor": "#F9FAFB"}'::jsonb,
  contact_mobile text,
  contact_email text,
  social_links jsonb DEFAULT '{}'::jsonb,
  legal_pages jsonb DEFAULT '{"terms": false, "refund": false, "privacy": false, "about_us": false}'::jsonb,
  meta_keywords text,
  meta_description text,
  custom_css text,
  custom_js text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_main_pkey PRIMARY KEY (id),
  CONSTRAINT fk_site_main_site FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.site_navigation (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL UNIQUE,
  header_logo_url text,
  header_logo_alt text,
  nav_items jsonb DEFAULT '[]'::jsonb,
  show_cart_icon boolean DEFAULT true,
  show_search boolean DEFAULT false,
  sticky_header boolean DEFAULT true,
  footer_columns jsonb DEFAULT '[]'::jsonb,
  footer_bottom_text text,
  social_links jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_navigation_pkey PRIMARY KEY (id)
);
CREATE TABLE public.site_page_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL,
  page_slug text,
  session_id text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  device_type USER-DEFINED,
  country_code character,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT site_page_views_pkey PRIMARY KEY (id)
);
CREATE TABLE public.site_product_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL,
  product_id uuid NOT NULL,
  placement text NOT NULL DEFAULT 'front_main'::text,
  is_visible boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_product_assignments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.site_sections_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL UNIQUE,
  site_type text NOT NULL CHECK (site_type IS NULL OR (site_type = ANY (ARRAY['main'::text, 'single'::text, 'payment'::text, 'linkinbio'::text]))),
  sections jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_sections_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.site_singlepage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL UNIQUE,
  product_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  hero_image_url text,
  template_name text DEFAULT 'modern'::text,
  theme jsonb DEFAULT '{"accentColor": "#8B5CF6", "primaryColor": "#6366F1"}'::jsonb,
  contact_mobile text,
  contact_email text,
  social_links jsonb DEFAULT '{}'::jsonb,
  legal_pages jsonb DEFAULT '{"terms": false, "refund": false, "privacy": false, "about_us": false}'::jsonb,
  show_add_to_cart boolean DEFAULT true,
  show_buy_now boolean DEFAULT true,
  enable_reviews boolean DEFAULT true,
  meta_description text,
  sections_config jsonb,
  countdown_end_at timestamp with time zone,
  social_proof_config jsonb,
  upsell_product_ids ARRAY,
  guarantee_badges jsonb DEFAULT '[]'::jsonb,
  faq_items jsonb DEFAULT '[]'::jsonb,
  testimonials jsonb DEFAULT '[]'::jsonb,
  custom_css text,
  custom_js text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_singlepage_pkey PRIMARY KEY (id),
  CONSTRAINT fk_sp_site FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT fk_sp_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.site_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_type text NOT NULL CHECK (site_type = ANY (ARRAY['main'::text, 'single'::text, 'payment'::text, 'linkinbio'::text])),
  template_key text NOT NULL,
  name text NOT NULL,
  description text,
  preview_image_url text,
  is_active boolean DEFAULT true,
  default_theme jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  slug text UNIQUE,
  child_slug text,
  parent_site_id uuid,
  site_type text DEFAULT 'main'::text CHECK (site_type IS NULL OR (site_type = ANY (ARRAY['main'::text, 'single'::text, 'payment'::text, 'blog'::text, 'builder'::text, 'linkinbio'::text]))),
  is_active boolean DEFAULT true,
  custom_domain text,
  domain_verified boolean DEFAULT false,
  ssl_status text DEFAULT 'none'::text CHECK (ssl_status = ANY (ARRAY['none'::text, 'pending'::text, 'active'::text, 'failed'::text])),
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT sites_pkey PRIMARY KEY (id),
  CONSTRAINT sites_parent_site_id_fkey FOREIGN KEY (parent_site_id) REFERENCES public.sites(id),
  CONSTRAINT fk_sites_creator FOREIGN KEY (creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.storage_file_usages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  file_id uuid NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  field_name text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT storage_file_usages_pkey PRIMARY KEY (id),
  CONSTRAINT fk_sfu_file FOREIGN KEY (file_id) REFERENCES public.storage_files(id)
);
CREATE TABLE public.storage_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider USER-DEFINED NOT NULL DEFAULT 'supabase'::storage_provider_type,
  provider_bucket text NOT NULL,
  provider_path text NOT NULL,
  cdn_url text NOT NULL,
  public_url text DEFAULT cdn_url,
  owner_user_id uuid,
  owner_creator_id uuid,
  file_name text,
  file_type text,
  mime_type text,
  size_bytes bigint CHECK (size_bytes > 0),
  checksum_sha256 text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'deleted'::text, 'migrating'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT storage_files_pkey PRIMARY KEY (id),
  CONSTRAINT fk_sf_user FOREIGN KEY (owner_user_id) REFERENCES public.users(id),
  CONSTRAINT fk_sf_creator FOREIGN KEY (owner_creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_type USER-DEFINED NOT NULL UNIQUE,
  plan_name text NOT NULL,
  platform_fee_percent numeric NOT NULL CHECK (platform_fee_percent >= 0::numeric AND platform_fee_percent <= 100::numeric),
  monthly_price numeric NOT NULL DEFAULT 0 CHECK (monthly_price >= 0::numeric),
  yearly_price numeric NOT NULL DEFAULT 0 CHECK (yearly_price >= 0::numeric),
  description text,
  features jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  subscription_plan_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'cancelled'::text, 'expired'::text, 'paused'::text])),
  billing_cycle text NOT NULL DEFAULT 'monthly'::text CHECK (billing_cycle = ANY (ARRAY['monthly'::text, 'yearly'::text])),
  current_price numeric NOT NULL DEFAULT 0 CHECK (current_price >= 0::numeric),
  current_platform_fee_percent numeric NOT NULL CHECK (current_platform_fee_percent >= 0::numeric AND current_platform_fee_percent <= 100::numeric),
  start_date timestamp with time zone DEFAULT now(),
  end_date timestamp with time zone,
  renewal_date timestamp with time zone,
  auto_renew boolean DEFAULT true,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_sub_creator FOREIGN KEY (creator_id) REFERENCES public.profiles(id),
  CONSTRAINT fk_sub_plan FOREIGN KEY (subscription_plan_id) REFERENCES public.subscription_plans(id)
);
CREATE TABLE public.transaction_ledger (
  id bigint NOT NULL DEFAULT nextval('transaction_ledger_id_seq'::regclass),
  user_id uuid,
  creator_id uuid,
  wallet_id uuid,
  order_id uuid,
  payout_id uuid,
  referral_id uuid,
  tx_type text NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency text NOT NULL DEFAULT 'INR'::text,
  direction USER-DEFINED NOT NULL,
  balance_after numeric,
  meta jsonb,
  prev_hash bytea,
  record_hash bytea NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT transaction_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ledger_user FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_ledger_creator FOREIGN KEY (creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.upsell_pages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  primary_product_id uuid NOT NULL,
  upsell_product_ids ARRAY DEFAULT '{}'::uuid[],
  config jsonb NOT NULL DEFAULT '{"theme": {"bg_color": "#FFFFFF", "text_color": "#0F172A", "primary_color": "#6366F1"}, "logo_url": "", "meta_title": "", "buy_now_label": "Buy Now", "contact_fields": {"show_name": true, "show_email": true, "show_phone": false}, "meta_description": "", "show_guarantee_badge": true}'::jsonb,
  is_published boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT upsell_pages_pkey PRIMARY KEY (id),
  CONSTRAINT upsell_pages_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.profiles(id),
  CONSTRAINT upsell_pages_primary_product_id_fkey FOREIGN KEY (primary_product_id) REFERENCES public.products(id)
);
CREATE TABLE public.user_carts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_carts_pkey PRIMARY KEY (id),
  CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.user_product_access (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  order_id uuid NOT NULL,
  order_item_id uuid,
  product_id uuid NOT NULL,
  product_name text NOT NULL,
  product_price numeric NOT NULL,
  product_link text NOT NULL,
  snapshot_metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_product_access_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referral_code_id uuid NOT NULL,
  referrer_user_id uuid,
  referrer_creator_id uuid,
  referred_user_id uuid NOT NULL,
  reward_status text DEFAULT 'pending'::text CHECK (reward_status = ANY (ARRAY['pending'::text, 'rewarded'::text])),
  reward_amount numeric,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_referrals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_wallet_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  wallet_id uuid NOT NULL,
  user_id uuid NOT NULL,
  related_order_id uuid,
  related_order_referral_id uuid,
  tx_type text NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  direction USER-DEFINED NOT NULL,
  balance_after numeric NOT NULL,
  status text DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text])),
  description text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_wallet_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_uwt_wallet FOREIGN KEY (wallet_id) REFERENCES public.user_wallets(id),
  CONSTRAINT fk_uwt_user FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_uwt_order FOREIGN KEY (related_order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.user_wallets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  balance numeric NOT NULL DEFAULT 0 CHECK (balance >= 0::numeric),
  currency text DEFAULT 'INR'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_wallets_pkey PRIMARY KEY (id),
  CONSTRAINT fk_wallet_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_wishlist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb,
  CONSTRAINT user_wishlist_pkey PRIMARY KEY (id),
  CONSTRAINT fk_wishlist_user FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_wishlist_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auth_provider_id uuid UNIQUE,
  email text UNIQUE,
  phone text UNIQUE,
  auth_provider text DEFAULT 'supabase'::text,
  is_verified boolean DEFAULT false,
  role text DEFAULT 'user'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);