'use client';

import React, { useState, useEffect } from 'react';
import { useEarnings } from '@/hooks/useEarnings';
import { createClient } from '@/lib/supabase/client';
import { ShieldCheck, Building2, UploadCloud, AlertCircle } from 'lucide-react';

export default function KYCAndBillingPage() {
  const { kyc, isLoading, refreshEarnings } = useEarnings();
  const supabase = createClient();
  
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [successMsg, setSuccessMsg] = useState('');
  
  const [formData, setFormData] = useState({
    legal_name: '',
    pan_enc: '', // Simplified as raw string for this DB mapping
    bank_account_enc: '',
    bank_account_name: '',
    ifsc_code: ''
  });

  useEffect(() => {
    if (kyc) {
      // Pre-fill existing data securely
      setFormData({
        legal_name: kyc.legal_name || '',
        pan_enc: kyc.pan_enc || '',
        bank_account_enc: kyc.bank_account_enc || '',
        bank_account_name: kyc.bank_account_name || '',
        ifsc_code: kyc.ifsc_code || ''
      });
    }
  }, [kyc]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMsg('');
    setSuccessMsg('');
    setIsSubmitting(true);

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Authentication required");

      const payload = {
        creator_id: user.id,
        legal_name: formData.legal_name,
        pan_enc: formData.pan_enc,
        bank_account_enc: formData.bank_account_enc,
        bank_account_name: formData.bank_account_name,
        ifsc_code: formData.ifsc_code,
        status: 'pending', // Re-trigger verification implicitly
        kyc_level: 'basic'
      };

      const { error } = await supabase
        .from('creator_kyc')
        .upsert(payload)
        .eq('creator_id', user.id);

      if (error) throw error;
      
      setSuccessMsg('KYC details submitted successfully! They are currently under review.');
      refreshEarnings();
      
    } catch (err: any) {
      console.error(err);
      setErrorMsg(err.message || 'Failed to submit KYC details.');
    } finally {
      setIsSubmitting(false);
    }
  };

  if (isLoading) {
    return <div className="p-8 text-center text-gray-500">Loading Configuration...</div>;
  }

  const isVerified = kyc?.status === 'verified';
  const isPending = kyc?.status === 'pending';
  const isRejected = kyc?.status === 'rejected';

  return (
    <div className="max-w-full space-y-6 pb-24">
      <div>
        <h1 className="text-2xl font-bold text-[var(--text-primary)]">Billing & KYC</h1>
        <p className="text-sm text-[var(--text-secondary)] mt-1">Configure your settlement accounts to receive payouts generated by your store.</p>
      </div>

      {isVerified && (
        <div className="bg-emerald-50 dark:bg-emerald-500/10 border border-emerald-200 dark:border-emerald-500/20 rounded-xl p-4 flex gap-3 items-start">
          <ShieldCheck className="w-5 h-5 text-emerald-600 dark:text-emerald-400 shrink-0 mt-0.5" />
          <div>
            <h3 className="text-sm font-bold text-emerald-800 dark:text-emerald-300">Identity Verified</h3>
            <p className="text-sm text-emerald-700/80 dark:text-emerald-400/80 mt-0.5">Your KYC and settlement accounts have been verified. You can withdraw available funds anytime.</p>
          </div>
        </div>
      )}

      {isPending && (
        <div className="bg-blue-50 dark:bg-blue-500/10 border border-blue-200 dark:border-blue-500/20 rounded-xl p-4 flex gap-3 items-start">
          <UploadCloud className="w-5 h-5 text-blue-600 dark:text-blue-400 shrink-0 mt-0.5" />
          <div>
            <h3 className="text-sm font-bold text-blue-800 dark:text-blue-300">Review Pending</h3>
            <p className="text-sm text-blue-700/80 dark:text-blue-400/80 mt-0.5">Your submitted information is currently being reviewed by our compliance team (typically 1-2 business days).</p>
          </div>
        </div>
      )}

      {isRejected && (
        <div className="bg-red-50 dark:bg-red-500/10 border border-red-200 dark:border-red-500/20 rounded-xl p-4 flex gap-3 items-start">
          <AlertCircle className="w-5 h-5 text-red-600 dark:text-red-400 shrink-0 mt-0.5" />
          <div>
            <h3 className="text-sm font-bold text-red-800 dark:text-red-300">Verification Rejected</h3>
            <p className="text-sm text-red-700/80 dark:text-red-400/80 mt-0.5">Please re-submit your details ensuring absolute accuracy.</p>
            {kyc?.rejection_reason && (
              <p className="text-sm font-mono mt-2 text-red-600">{kyc.rejection_reason}</p>
            )}
          </div>
        </div>
      )}

      <form onSubmit={handleSubmit} className="bg-[var(--bg-primary)] border border-[var(--border)] rounded-2xl shadow-sm overflow-hidden">
        
        {/* Identity Context */}
        <div className="px-6 py-6 border-b border-[var(--border)] space-y-5">
           <h2 className="text-lg font-bold text-[var(--text-primary)]">Personal Identity (PAN)</h2>
           
           <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
             <div>
                <label className="block text-sm font-medium text-[var(--text-primary)] mb-1.5">Legal Name</label>
                <input 
                  type="text"
                  required
                  value={formData.legal_name}
                  onChange={e => setFormData({ ...formData, legal_name: e.target.value })}
                  disabled={isVerified || isPending}
                  className="w-full px-4 py-2.5 bg-[var(--bg-secondary)] border border-[var(--border)] rounded-xl focus:ring-2 focus:ring-[var(--accent)]/40 outline-none text-[var(--text-primary)] disabled:opacity-60"
                  placeholder="As per PAN card"
                />
             </div>
             <div>
                <label className="block text-sm font-medium text-[var(--text-primary)] mb-1.5">PAN Number</label>
                <input 
                  type="text"
                  required
                  value={formData.pan_enc}
                  onChange={e => setFormData({ ...formData, pan_enc: e.target.value.toUpperCase() })}
                  disabled={isVerified || isPending}
                  className="w-full px-4 py-2.5 bg-[var(--bg-secondary)] border border-[var(--border)] rounded-xl focus:ring-2 focus:ring-[var(--accent)]/40 outline-none text-[var(--text-primary)] font-mono disabled:opacity-60 uppercase"
                  placeholder="ABCDE1234F"
                />
             </div>
           </div>
        </div>

        {/* Bank Context */}
        <div className="px-6 py-6 space-y-5">
           <div className="flex items-center gap-3 mb-2">
             <Building2 className="w-5 h-5 text-[var(--text-secondary)]" />
             <h2 className="text-lg font-bold text-[var(--text-primary)]">Settlement Bank Account</h2>
           </div>
           
           <div>
              <label className="block text-sm font-medium text-[var(--text-primary)] mb-1.5">Account Holder Name</label>
              <input 
                type="text"
                required
                value={formData.bank_account_name}
                onChange={e => setFormData({ ...formData, bank_account_name: e.target.value })}
                disabled={isVerified || isPending}
                className="w-full px-4 py-2.5 bg-[var(--bg-secondary)] border border-[var(--border)] rounded-xl focus:ring-2 focus:ring-[var(--accent)]/40 outline-none text-[var(--text-primary)] disabled:opacity-60"
                placeholder="Must match Legal Name exactly"
              />
           </div>

           <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
             <div>
                <label className="block text-sm font-medium text-[var(--text-primary)] mb-1.5">Account Number</label>
                <input 
                  type="password"
                  required
                  value={formData.bank_account_enc}
                  onChange={e => setFormData({ ...formData, bank_account_enc: e.target.value })}
                  disabled={isVerified || isPending}
                  className="w-full px-4 py-2.5 bg-[var(--bg-secondary)] border border-[var(--border)] rounded-xl focus:ring-2 focus:ring-[var(--accent)]/40 outline-none text-[var(--text-primary)] font-mono disabled:opacity-60"
                />
             </div>
             <div>
                <label className="block text-sm font-medium text-[var(--text-primary)] mb-1.5">IFSC Code</label>
                <input 
                  type="text"
                  required
                  value={formData.ifsc_code}
                  onChange={e => setFormData({ ...formData, ifsc_code: e.target.value.toUpperCase() })}
                  disabled={isVerified || isPending}
                  className="w-full px-4 py-2.5 bg-[var(--bg-secondary)] border border-[var(--border)] rounded-xl focus:ring-2 focus:ring-[var(--accent)]/40 outline-none text-[var(--text-primary)] font-mono disabled:opacity-60 uppercase"
                  placeholder="SBIN0001234"
                />
             </div>
           </div>
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-5 border-t border-[var(--border)] bg-[var(--bg-secondary)] flex flex-col sm:flex-row justify-between items-center gap-4">
          <div className="flex-1">
            {errorMsg && <p className="text-sm font-medium text-red-600">{errorMsg}</p>}
            {successMsg && <p className="text-sm font-medium text-emerald-600">{successMsg}</p>}
          </div>

          {!isVerified && !isPending && (
            <button 
              type="submit" 
              disabled={isSubmitting}
              className="w-full sm:w-auto bg-black dark:bg-white text-white dark:text-black hover:bg-gray-800 dark:hover:bg-gray-200 disabled:opacity-50 px-8 py-3 rounded-xl font-bold transition shadow-sm"
            >
              {isSubmitting ? 'Submitting...' : 'Submit for Verification'}
            </button>
          )}
        </div>

      </form>
    </div>
  );
}
